### ISSUE TITLE
Make the OAuth tokens less annoying to deal with

### ISSUE THREAD

**Issue by DaniloHP** [arkenproject/ait#61]
Possible options, from least to most desirable, include:
- Saving it in `~/.ait/ait.config`
- Saving it as an environment variable
- Saving it somewhere else, but fully encrypted. User would set a passkey to unlock it with.

Also, I should look into how to get that OAuth prompt to come up in the browser.

**Comment by alecbcs** [comment]
Closing with merge of PR. Nice Job Danilo!
